# golangci-lint configuration options

linters:
  enable:
    - deadcode
    - errcheck
    - goimports
    - revive
    - ineffassign
    - structcheck
    - varcheck
    - govet
    - unconvert
    #- prealloc
    #- maligned
  disable-all: true

issues:
  # Enable some lints excluded by default
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
